#let openings = (
  ("DoS/ISRO Internship & Student Project Trainee Schemes", "➖", "IN", "https://www.isro.gov.in/InternshipAndProjects.html"),
  ("Visiting Student Research Program at KAUST", "➖", "IN", "https://admissions.kaust.edu.sa/study/internships"),
  ("Max Planck Institute for Informatics - PhD Applications", "➖", "PH", "https://www.mpi-inf.mpg.de/departments/computer-vision-and-machine-learning/application/phd-applications?utm_source=chatgpt.com"),
  ("UC Berkeley's Physics Graduate Program", "2025-12-15", "PH", "https://physics.berkeley.edu/academic/graduate-degree/graduate-admissions?utm_source=chatgpt.com"),
  ("Arizona State University Physics PhD Admission", "2026-01-31", "PH", "https://physics.asu.edu/admissions/phd-admissions?utm_source=chatgpt.com"),
  ("Exoplanet Characterisation Predictions via Gravitational Microlensing: Competition Funded PhD Project", "➖", "PH", "https://www.findaphd.com/phds/project/exoplanet-characterisation-predictions-via-gravitational-microlensing/?p171628"),
  ("HRDG- Nehru Science Postdoctoral research Fellowship", "➖", "PD", "https://csirhrdg.res.in/Home/Index/1/Default/3419/55?s=08"),
  ("Maria de Maeztu Postdoctoral position in Gravitational Waves Astronomy at the ICCUB", "2025-11-30", "PD", "https://www.lisamission.org/maria-de-maeztu-postdoctoral-position-in-gravitational-waves-astronomy-at-the-iccub/"),
  ("University of Chicago Graduate School Programme", "➖", "PH", "https://grad.uchicago.edu/admissions/apply/guidelines-and-deadlines/"),
  ("University of Texas at Austin Graduate School Programme", "➖", "PH", "https://students.gradschool.utexas.edu/portal/app"),
  ("University of Utah Graduate School Programme", "➖", "PH", "https://admissions.utah.edu/apply/graduate-students/"),
  ("Training as a Material Tester", "2025-12-30", "IN", "https://bewerbermanagement.net/jobposting/f98c4a12019eb449bdf373a5ccc2ff1c02b4fbaf0"),
  ("University of North Carolina at Chapel Hill PhD Programme", "2025-12-16", "PH", "https://gradschool.unc.edu/degree-programs/"),
  ("University of North Carolina at Charlotte PhD Programme", "2025-12-01", "PH", "https://gradadmissions.charlotte.edu/apply-now/application-requirements/#deadlines"),
  ("Louisiana State University PhD Programme", "➖", "PH", "https://www.lsu.edu/graduateschool/admissions/requirements-deadlines.php"),
  ("PhD Position - EPFL", "➖", "PH", "https://www.linkedin.com/posts/florian-schueder-318b02148_open-position-phd-student-activity-7356598175018680320-gW2R?utm_source=share&utm_medium=member_desktop&rcm=ACoAADc_xDABBm9oWnlmA0AAJye9s7W9iDd-frw"),
  ("Post Doctoral Position at Institute of Physical Chemistry, Polish Academy of Sciences", "2025-12-31", "PD", "https://bs4s.edu.pl/"),
  ("PhD Position (m/f/d) | Decoding symbiont establishment through systems modeling and multi-omics integration", "2025-12-15", "PH", "https://www.mpg.de/25693802/phd-position"),
  ("Postdoctoral position (m/f/d) | High-redshift galaxy / black hole evolution", "2025-12-17", "PD", "https://www.mpg.de/25693900/postdoctoral-position-in-high-redshift-galaxy-black-hole-evolution"),
  ("Research Engineer – Software Development or DevOps (m/f/d)", "2025-11-30", "PD", "https://www.mpg.de/25687309/research-engineer-software-development-or-devops-tue-100"),
  ("Fully funded doctoral positions | Epigenetics, Biophysics and Metabolism", "2026-02-06", "PH", "https://www.mpg.de/25677864/fully-funded-doctoral-positions-imprs-ebm"),
  ("PhD student (m/f/d)", "2026-01-31", "PH", "https://www.mpg.de/25676082/phd-student-2025-37"),
  ("Postdoctoral positions | Computational Relativistic Astrophysics", "2025-12-21", "PD", "https://www.mpg.de/25654088/postdoctoral-positions-computational-relativistic-astrophysics"),
  ("Postdoc position (m/f/d) | Development and Application of an Ultra-Bright Coherent Soft X-Ray Beamline", "➖", "PD", "https://www.mpg.de/25649454/postdoc-x-ray-beamline"),
  ("Doctoral (PhD) and postdoctoral position (m/f/d) in Computational Biology | Biomathematics | Biosystems Engineering", "➖", "PD", "https://www.mpg.de/25622528/doctoral-phd-and-postdoctoral-position-computational-biology-biomathematics-biosystems-engineering"),
  ("Doctoral (PhD) and postdoctoral position (m/f/d) in Computational Biology | Biomathematics | Biosystems Engineering", "➖", "PH", "https://www.mpg.de/25622528/doctoral-phd-and-postdoctoral-position-computational-biology-biomathematics-biosystems-engineering"),
  ("Associate/Full Professor Tropical Meteorology, Dept. of Geography, University of Georgia", "2025-12-12", "PD", "https://findajob.agu.org/job/8025880/associate-full-professor-tropical-meteorology-dept-of-geography-university-of-georgia/?TrackID=35896&BatchID=17786&JobAlertId=54257&cmpid=JBE_TL_20251113_jobtitle&utm_source=jbe&utm_medium=email&utm_campaign=JBE_TL_20251113_applynow_job1"),
  ("Assistant Professor - Geomorphology of Ocean Islands", "2026-01-12", "PD", "https://findajob.agu.org/job/8025892/assistant-professor-geomorphology-of-ocean-islands/?TrackID=35896&BatchID=17786&JobAlertId=54257&cmpid=JBE_TL_20251113_jobtitle&utm_source=jbe&utm_medium=email&utm_campaign=JBE_TL_20251113_applynow_job2"),
  ("Associate or Full Professor, Weather Ready Texas Cluster", "2025-12-12", "PD", "https://findajob.agu.org/job/8025884/associate-or-full-professor-weather-ready-texas-cluster/?TrackID=35896&BatchID=17786&JobAlertId=54257&cmpid=JBE_TL_20251113_jobtitle&utm_source=jbe&utm_medium=email&utm_campaign=JBE_TL_20251113_applynow_job3"),
  ("Director, School of Earth and Space Exploration", "2025-12-12", "PD", "https://findajob.agu.org/job/8025883/director-school-of-earth-and-space-exploration/?TrackID=35896&BatchID=17786&JobAlertId=54257&cmpid=JBE_TL_20251113_jobtitle&utm_source=jbe&utm_medium=email&utm_campaign=JBE_TL_20251113_applynow_job4"),
  ("Ph.D. Student Opportunity (Computational hydrology)", "2025-12-12", "PH", "https://findajob.agu.org/job/8025878/ph-d-student-opportunity-computational-hydrology-/?TrackID=35896&BatchID=17786&JobAlertId=54257&cmpid=JBE_TL_20251113_jobtitle&utm_source=jbe&utm_medium=email&utm_campaign=JBE_TL_20251113_applynow_job5"),
  ("Doctoral (PhD) and postdoctoral position (m/f/d) in Computational Biology | Biomathematics | Biosystems Engineering", "➖", "PH", "https://www.mpg.de/25622528/doctoral-phd-and-postdoctoral-position-computational-biology-biomathematics-biosystems-engineering"),
  ("Doctoral (PhD) position (m/f/d) in Glia Biology | Neurobiology at the Dioscuri Centre for Chromatin Biology and Epigenomics at the Nencki Institute for Experimental biology (Poland)", "➖", "PH", "https://www.mpg.de/job-f9fbf66ad122669a970d1fe58b3cab06"),
  ("Postdoc/Research Scientist in the Reproductive Ageing Research Group (m/f/d)", "➖", "PD", "https://www.mpg.de/25716051/postdoc-research-scientist-in-the-reproductive-ageing-research-group"),
  ("PhD Position: Job Code: CF-06-2025", "2026-01-11", "PH", "https://www.mpg.de/job-9b5ecc5526b75d78d8c10511f7b8e858")
)